#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System' -width 12 -hide-scrollbar -line-padding 4 -padding 20 -lines 5 <<< " Lock| Logout|⏾ Suspend| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) xflock4;;
                *Logout) bspc quit;;
                *Suspend) systemctl suspend;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
