#! /bin/sh

commands=(
  "xrdb merge .Xresources"
  "xset +fp /usr/share/fonts/misc"
  "xset fp rehash"
  "fc-cache -fv"
  "xset +dpms"
  "volnoti"
  "thunar --daemon"
  "deadd-notification-center"
  "system-config-printer-applet"
  "start-pulseaudio-x11"
  "xfce4-power-manager"
  "xfce4-screensaver"
  "/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1"
  "nm-applet"
  "/usr/bin/gnome-keyring-daemon --start --components=ssh,secrets,pkcs11"
  "/usr/bin/caffeine"
  "blueman-applet"
  "dropbox"
  "pasystray"
)

for cmd in "${commands[@]}"; do
  ${cmd} &
done

dex -a -s ~/.config/autostart/ &
