#! /bin/sh

"${XDG_CONFIG_HOME:-"$HOME/.config"}"/bspwm/setup_workspaces &

gap=5
bspc config window_gap $gap
bspc config top_padding $gap
bspc config left_padding $gap
bspc config right_padding $gap
bspc config bottom_padding $gap
bspc config split_ratio 0.5

bspc config gapless_monocle true
bspc config borderless_monocle true
bspc config single_monocle true
bspc config top_monocle_padding $gap
bspc config left_monocle_padding $gap
bspc config right_monocle_padding $gap
bspc config bottom_monocle_padding $gap
bspc config remove_disabled_monitors false
bspc config remove_unplugged_monitors false

bspc config focused_border_color "#dddddd"
bspc config normal_border_color "#2D2D2D"
bspc config presel_feedback_color "#1ABB9B"
bspc config border_width 2

bspc config focus_follows_pointer true
bspc config pointer_follows_monitor true

bspc rule -a spotify state=pseudo_tiled
bspc rule -a Emacs state=tiled
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a Xfce4-notifyd state=floating manage=on layer=above sticky=on follow=off
bspc rule -a '*:origin.exe' state=floating manage=off
bspc rule -a '*:Origin' state=floating manage=off
bspc rule -a '*:*:Bullet Physics ExampleBrowser using OpenGL3+ [btgl] Release build' state=floating manage=off

bspc subscribe monitor | while read -r line; do
  case $line in
    monitor_add*|monitor_remove*)
      autorandr --change
      ~/.config/bspwm/display_reconfigure
    ;;
    *)
    ;;
  esac
done &
