#! /bin/sh

# Startup programs
udiskie &
sxhkd &
~/.screenlayout/default.sh &
~/bgscript.sh &
picom -CGb &
xmodmap ~/.Xmodmap &
~/.config/polybar/launch.sh &
nm-applet &
volnoti &
caffeine &
#xcape -e 'Super_L=Super_L|Shift_L|space' &

gap=10
PANEL_HEIGHT=25
export gap
export PANEL_HEIGHT

bspc config window_gap $gap;
bspc config top_padding $(($PANEL_HEIGHT+$gap))
bspc config left_padding $gap
bspc config right_padding $gap
bspc config bottom_padding $gap

#Various settings
bspc config gapless_monocle     true 
bspc config borderless_monocle  true
bspc config single_monocle true
bspc config top_monocle_padding $gap
bspc config left_monocle_padding $gap
bspc config right_monocle_padding $gap
bspc config bottom_monocle_padding $gap
# bspc config paddingless_monocle false
#bspc config ignore_ewmh_focus      true
#bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

workspaces_multimonitor &

##Color settings
bspc config focused_border_color "#dddddd"
bspc config normal_border_color "#2D2D2D"
bspc config presel_feedback_color "#1ABB9B"
bspc config border_width 2

bspc config focus_follows_pointer true
bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc config split_ratio          0.52

bspc rule -a screenkey --unmanage
bspc rule -a gcolor2 state=floating center=true
bspc rule -a lxappearance state=floating center=true
bspc rule -a gmrun state=floating center=true
bspc rule -a lxterminal state=floating center=true sticky=true
#bspc rule -a urxvt state=floating center=true
bspc rule -a viewnior state=floating center=true
bspc rule -a file-roller state=floating center=true
bspc rule -a floaterm state=floating center=true
bspc rule -a spotify state=pseudo_tiled
#bspc rule -a nautilus state=pseudo_tiled
#bspc rule -a skype state=pseudo_tiled
bspc rule -a file-roller state=pseudo_tiled
bspc rule -a transmission-gtk state=pseudo_tiled
bspc rule -a conky sticky=on manage=off lower=on
bspc rule -a astime sticky=on
bspc rule -a yad state=floating
bspc rule -a Docky layer=above border=off manage=on
bspc rule -a Plank layer=above border=off manage=on
bspc rule -a wbar layer=above
bspc rule -a dockbarx layer=above
bspc rule -a google-chrome-unstable private=on
bspc rule -a google-chrome-stable private=on
bspc rule -a chromium private=on
bspc rule -a firefox private=on
bspc rule -a Emacs state=tiled
bspc rule -a midori private=on
bspc rule -a gnome-pie border=off manage=off
bspc rule -a wpa_gui state=pseudo_tiled
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
#bspc rule -a firefox desktop=I
#bspc rule -a calibre desktop=II
#bspc rule -a geany desktop=II
#bspc rule -a deluge desktop=III
bspc rule -a 9menu border=off manage=off
bspc rule -a tint2 border=off manage=off
#bspc desktop I --layout monocle
#bspc desktop II --layout monocle

#bspc config external_rules_command /usr/bin/pseudo_automatic_mode
