#! /bin/sh

function on_exit() {
  for child in $(jobs -p); do
    jobs -p | grep -q $child && kill $child
  done
}

trap on_exit EXIT SIGHUP SIGINT SIGTERM

export SESSION_MANAGER=lightdm
# To deal with gray window and non-resizing problems in Java GUIs
export _JAVA_AWT_WM_NONREPARENTING=1
source_these=(
  "/etc/profile"
  "${HOME}/.profile"
  "${XDG_CONFIG_HOME:-"$HOME/.config"}/bspwm/display_setup"
  "${XDG_CONFIG_HOME:-"$HOME/.config"}/bspwm/autostart"
)

for file in "${source_these[@]}"; do
  [ -r "${file}" ] && . "${file}"
done

[ -e /bin/dash ] && SXHKD_SHELL="/bin/dash"
sxhkd &

bspwm
