#! /bin/sh

export SXHKD_SHELL=sh
# Startup programs
sxhkd &
picom -CGb &
# xmodmap ~/.Xmodmap &
if [ -z $KDEWM ]
then
  ~/.config/polybar/launch.sh &
  udiskie &
  ~/bgscript.sh &
  nm-applet &
  volnoti &
  caffeine &
else
  latte-dock --replace &
fi

# xcape -e 'Super_L=Super_L|Shift_L|space' &

gap=10
PANEL_HEIGHT=25
export gap
export PANEL_HEIGHT

bspc config window_gap $gap
bspc config top_padding $gap
bspc config left_padding $gap
bspc config right_padding $gap
bspc config bottom_padding $gap

#Various settings
bspc config gapless_monocle     true 
bspc config borderless_monocle  true
bspc config single_monocle true
bspc config top_monocle_padding $gap
bspc config left_monocle_padding $gap
bspc config right_monocle_padding $gap
bspc config bottom_monocle_padding $gap
# bspc config paddingless_monocle false
#bspc config ignore_ewmh_focus      true
#bspc config initial_polarity second_child
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

workspaces_multimonitor &

##Color settings
bspc config focused_border_color "#dddddd"
bspc config normal_border_color "#2D2D2D"
bspc config presel_feedback_color "#1ABB9B"
bspc config border_width 2

bspc config focus_follows_pointer true
# bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true

bspc config split_ratio          0.52

bspwm_root_id=$(xdo id -N Bspwm -n root | sort | head -n 1)
for wid in $(xdotool search --class plasmashell); do xdo below -t $bspwm_root_id $wid; done

bspc rule -a spotify state=pseudo_tiled
bspc rule -a Emacs state=tiled
bspc rule -a libreoffice state=tiled
bspc rule -a '*:libreofficedev' state=tiled
bspc rule -a '*:soffice' state=tiled
bspc rule -a plasmashell state=floating border=off layer=normal
bspc rule -a krunner state=floating border=off
bspc rule -a lattedock border=off state=floating

#bspc config external_rules_command /usr/bin/pseudo_automatic_mode
#~/.screenlayout/default.sh &
