#! /bin/sh

# "${HOME}"/.screenlayout/default.sh
autorandr --change
"${XDG_CONFIG_HOME:-"$HOME/.config"}"/bspwm/setup_workspaces &
"${XDG_CONFIG_HOME:-"$HOME/.config"}"/polybar/launch.sh &
"${HOME}"/bgscript.sh &
