#!/bin/bash

## Created By Aditya Shakya

#MENU="$(rofi -sep "|" -dmenu -i -p 'System' -location 5 -xoffset -14 -yoffset -52 -width 10 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< " Lock| Logout| Reboot| Shutdown")"
MENU="$(rofi -sep "|" -dmenu -i -p 'System' \
-location 3 -xoffset -10 -yoffset 35 -width 10 \
-hide-scrollbar -line-padding 4 -padding 20 -lines 5 \
-show-icons -icon-theme "Papirus" -font "Lato 12" \
-color-enabled true \
<<< " Lock| Logout|⏾ Suspend| Reboot| Shutdown")"
            case "$MENU" in
                *Lock) xflock4 ;;
                *Logout) bspc quit;;
                *Suspend) systemctl suspend;;
                *Reboot) systemctl reboot ;;
                *Shutdown) systemctl -i poweroff
            esac
