# plug.kak
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug 'andreyorst/plug.kak' noload config %{
  set-option global plug_always_ensure true
  hook global WinSetOption filetype=plug %{
  	remove-highlighter buffer/numbers
  	remove-highlighter buffer/matching
  	remove-highlighter buffer/wrap
  	remove-highlighter buffer/show-whitespaces
  	map buffer normal 'q' ':delete-buffer<ret>' -docstring 'close updates buffer'
  }
}

# Colorscheme
plug 'AprilArcus/base16-kakoune' theme config %{
  colorscheme base16-grayscale-dark
}

# Text objects
plug "delapouite/kakoune-text-objects"

# Surround
plug 'h-youhei/kakoune-surround' config %{
   declare-user-mode surround
   map global surround s ':surround<ret>' -docstring 'surround'
   map global surround c ':change-surround<ret>' -docstring 'change'
   map global surround d ':delete-surround<ret>' -docstring 'delete'
   map global surround t ':select-surrounding-tag<ret>' -docstring 'select tag'
}

# Vertical selection
plug "occivink/kakoune-vertical-selection"

# Powerline
# plug 'andreyorst/powerline.kak'

# FZF
plug "andreyorst/fzf.kak"
set-option global fzf_file_command 'fd'

# Tabs/indentation
set-option global tabstop 2
set-option global indentwidth 2

plug "andreyorst/smarttab.kak" config %{
  #set-option global softtabstop 2
  expandtab
}
   
# LSP
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
	set-option window lsp_auto_highlight_references true
	set-option window lsp_hover_anchor false
	lsp-auto-hover-enable
  lsp-enable-window
}

hook global KakEnd .* lsp-exit

set-option global lsp_server_configuration pyls.configurationSources=["flake8"]

# Line numbers
add-highlighter global/ number-lines -relative -hlcursor -separator ' '

# Matches
add-highlighter global/ show-matching

# Scrolloff
set-option global scrolloff 5,5

# Git diff
hook global -group fly-git NormalIdle .* %{ try %{ git show-diff } }
hook global -group fly-git InsertIdle .* %{ try %{ git show-diff } }

# Commenting
#map global normal '<c-/>' ':comment-line<ret>'
